import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Report, ReportData, ReportType } from "../types";

const REPORT_TYPE_LABELS: Record<ReportType, string> = {
  sales: "Sales Report",
  inventory: "Inventory",
  job_order: "Job Order",
  staff_performance: "Staff Report",
};

const NEUTRAL_950: [number, number, number] = [10, 10, 10];
const NEUTRAL_600: [number, number, number] = [115, 115, 115];
const NEUTRAL_200: [number, number, number] = [229, 229, 229];

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
}

function flattenObj(
  obj: Record<string, unknown>,
  prefix = ""
): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}_${key}` : key;
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(result, flattenObj(value as Record<string, unknown>, newKey));
    } else {
      result[newKey] = value;
    }
  }
  return result;
}

function formatLabel(key: string): string {
  return key
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function generateReportPDF(
  report: Report,
  data: ReportData,
  primaryColorHex = "#5570F1"
): void {
  const PRIMARY_COLOR = hexToRgb(primaryColorHex);
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  let y = margin;

  // ─── Header ───
  doc.setFillColor(...PRIMARY_COLOR);
  doc.rect(0, 0, pageWidth, 36, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(report.report_name, margin, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(220, 230, 255);
  doc.text(
    `${REPORT_TYPE_LABELS[report.report_type]}  |  ${report.branches?.name || "All Branches"}  |  Generated ${new Date(report.generated_at).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}`,
    margin,
    26
  );

  y = 44;

  // ─── Report Details (details + summary combined) ───
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...NEUTRAL_950);
  doc.text("Report Details", margin, y);
  y += 6;

  const allDetails: [string, string][] = [
    ["Report Type", REPORT_TYPE_LABELS[report.report_type]],
    ["Branch", report.branches?.name || "All Branches"],
    ["Generated By", report.user_profiles?.full_name || "Unknown"],
  ];

  if (report.filters?.date_from) {
    allDetails.push(["Start Date", report.filters.date_from]);
  }
  if (report.filters?.date_to) {
    allDetails.push(["End Date", report.filters.date_to]);
  }

  // Append summary entries as detail lines
  if (data.summary && Object.keys(data.summary).length > 0) {
    for (const [key, value] of Object.entries(data.summary)) {
      const displayValue =
        typeof value === "object"
          ? Object.entries(value as Record<string, unknown>)
              .map(([k, v]) => `${k}: ${v}`)
              .join(", ")
          : typeof value === "number"
          ? value.toLocaleString()
          : String(value);
      allDetails.push([formatLabel(key), displayValue]);
    }
  }

  doc.setFontSize(9);
  for (const [label, value] of allDetails) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...NEUTRAL_600);
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NEUTRAL_950);
    doc.text(value, margin + 40, y);
    y += 5;
  }

  y += 6;

  // ─── Data Table ───
  if (data.rows.length > 0) {

    const flatRows = data.rows.map((row) => flattenObj(row));
    const headers = Object.keys(flatRows[0]!).slice(0, 8);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [headers.map(formatLabel)],
      body: flatRows.map((row) =>
        headers.map((h) => {
          const v = row[h];
          return v !== null && v !== undefined ? String(v) : "—";
        })
      ),
      styles: {
        fontSize: 7,
        cellPadding: 2.5,
        textColor: NEUTRAL_950,
        lineColor: NEUTRAL_200,
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: PRIMARY_COLOR,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 7.5,
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250],
      },
      didDrawPage: (hookData) => {
        // Footer on each page
        const pageCount = doc.getNumberOfPages();
        const currentPage = hookData.pageNumber;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(...NEUTRAL_600);
        doc.text(
          `Page ${currentPage} of ${pageCount}`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 8,
          { align: "center" }
        );
        doc.text(
          report.report_name,
          margin,
          doc.internal.pageSize.getHeight() - 8
        );
      },
    });
  } else {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...NEUTRAL_600);
    doc.text("No data found for this report configuration.", margin, y + 8);
  }

  // Save
  const filename = report.report_name
    .replace(/[^a-zA-Z0-9_\- ]/g, "")
    .replace(/\s+/g, "_");
  doc.save(`${filename}.pdf`);
}
