import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import type { Report, ReportData, ReportType } from "../types";

const REPORT_TYPE_LABELS: Record<ReportType, string> = {
  sales: "Sales Report",
  inventory: "Inventory",
  job_order: "Job Order",
  staff_performance: "Staff Report",
};

function hexToArgb(hex: string): string {
  return "FF" + hex.replace("#", "").toUpperCase();
}

function flattenObj(
  obj: Record<string, unknown>,
  prefix = ""
): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}_${key}` : key;
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(result, flattenObj(value as Record<string, unknown>, newKey));
    } else {
      result[newKey] = value;
    }
  }
  return result;
}

function formatLabel(key: string): string {
  return key
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function truncateId(value: unknown): string {
  const str = String(value);
  if (str.length > 20 && /^[a-f0-9-]{20,}$|^[a-zA-Z0-9_-]{20,}$/.test(str)) {
    return str.substring(0, 4) + "-" + str.substring(str.length - 4);
  }
  return str;
}

export async function generateReportExcel(
  report: Report,
  data: ReportData,
  primaryColorHex = "#5570F1"
): Promise<void> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Petrozone Pulse";
  wb.created = new Date();

  const ws = wb.addWorksheet("Report", {
    properties: { defaultColWidth: 18 },
  });

  const primaryArgb = hexToArgb(primaryColorHex);
  const borderColor: Partial<ExcelJS.Border> = {
    style: "thin",
    color: { argb: "FFE5E5E5" },
  };
  const thinBorder: Partial<ExcelJS.Borders> = {
    top: borderColor,
    bottom: borderColor,
    left: borderColor,
    right: borderColor,
  };

  // Determine table column count first (for header span)
  const flatRows = data.rows.length > 0 ? data.rows.map((row) => flattenObj(row)) : [];
  const headers = flatRows.length > 0 ? Object.keys(flatRows[0]!).slice(0, 8) : [];
  const colSpan = Math.max(headers.length, 2);

  let rowIndex = 1;

  // ─── Header row ───
  const headerRow = ws.getRow(rowIndex);
  ws.mergeCells(rowIndex, 1, rowIndex, colSpan);
  const headerCell = ws.getCell(rowIndex, 1);
  headerCell.value = report.report_name;
  headerCell.font = { bold: true, size: 16, color: { argb: "FFFFFFFF" } };
  headerCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: primaryArgb },
  };
  headerCell.alignment = { vertical: "middle", horizontal: "left" };
  headerRow.height = 36;
  rowIndex++;

  // ─── Subtitle row ───
  ws.mergeCells(rowIndex, 1, rowIndex, colSpan);
  const subtitleCell = ws.getCell(rowIndex, 1);
  subtitleCell.value = `${REPORT_TYPE_LABELS[report.report_type]}  |  ${report.branches?.name || "All Branches"}  |  Generated ${new Date(report.generated_at).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}`;
  subtitleCell.font = { size: 10, color: { argb: "FF737373" }, italic: true };
  subtitleCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: primaryArgb },
  };
  subtitleCell.alignment = { vertical: "middle" };
  ws.getRow(rowIndex).height = 22;
  rowIndex += 2;

  // ─── Report Details (details + summary combined) ───
  const allDetails: [string, string][] = [
    ["Report Type", REPORT_TYPE_LABELS[report.report_type]],
    ["Branch", report.branches?.name || "All Branches"],
    ["Generated By", report.user_profiles?.full_name || "Unknown"],
  ];
  if (report.filters?.date_from) allDetails.push(["Start Date", report.filters.date_from]);
  if (report.filters?.date_to) allDetails.push(["End Date", report.filters.date_to]);

  // Append summary entries as detail lines
  if (data.summary && Object.keys(data.summary).length > 0) {
    for (const [key, value] of Object.entries(data.summary)) {
      const displayValue =
        typeof value === "object"
          ? Object.entries(value as Record<string, unknown>)
              .map(([k, v]) => `${k}: ${v}`)
              .join(", ")
          : typeof value === "number"
          ? value.toLocaleString()
          : String(value);
      allDetails.push([formatLabel(key), displayValue]);
    }
  }

  for (const [label, value] of allDetails) {
    const labelCell = ws.getCell(rowIndex, 1);
    const valueCell = ws.getCell(rowIndex, 2);
    labelCell.value = label;
    labelCell.font = { bold: true, size: 10, color: { argb: "FF737373" } };
    valueCell.value = value;
    valueCell.font = { size: 10, color: { argb: "FF0A0A0A" } };
    rowIndex++;
  }

  rowIndex += 1;

  // ─── Data Table ───
  if (headers.length > 0) {
    // Table header
    for (let i = 0; i < headers.length; i++) {
      const cell = ws.getCell(rowIndex, i + 1);
      cell.value = formatLabel(headers[i]!);
      cell.font = { bold: true, size: 9, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: primaryArgb },
      };
      cell.alignment = { vertical: "middle", horizontal: "left" };
      cell.border = thinBorder;
    }
    ws.getRow(rowIndex).height = 24;
    rowIndex++;

    // Table body
    for (let r = 0; r < flatRows.length; r++) {
      const row = flatRows[r]!;
      const isAlt = r % 2 === 1;
      for (let i = 0; i < headers.length; i++) {
        const cell = ws.getCell(rowIndex, i + 1);
        const v = row[headers[i]!];
        cell.value = v !== null && v !== undefined ? truncateId(v) : "—";
        cell.font = { size: 9, color: { argb: "FF0A0A0A" } };
        cell.border = thinBorder;
        if (isAlt) {
          cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: "FFFAFAFA" },
          };
        }
      }
      rowIndex++;
    }

    // Auto-fit columns
    for (let i = 1; i <= headers.length; i++) {
      const col = ws.getColumn(i);
      let maxLen = formatLabel(headers[i - 1]!).length;
      for (const row of flatRows) {
        const v = row[headers[i - 1]!];
        const len = v !== null && v !== undefined ? String(v).length : 1;
        if (len > maxLen) maxLen = len;
      }
      col.width = Math.min(Math.max(maxLen + 4, 12), 40);
    }
  }

  // Generate and save
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const filename = report.report_name
    .replace(/[^a-zA-Z0-9_\- ]/g, "")
    .replace(/\s+/g, "_");
  saveAs(blob, `${filename}.xlsx`);
}
